#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

set -x 

yabai -m config external_bar all:40:0

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 1 --label browse
yabai -m space 2 --label dev
yabai -m space 3 --label chat
yabai -m space 4 --label scratch

yabai -m config debug_output on

yabai -m config layout bsp
yabai -m config window_placement second_child

yabai -m config top_padding    8 
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

yabai -m config focus_follows_mouse autofocus 
yabai -m config mouse_follows_focus on

yabai -m config window_shadow float

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^kitty$" manage=off sticky=on grid=1:1:1:1:1:1

##########################################
# OPEN APPS IN THEIR RESPECTIVE SPACES
########################################## 

# browse
yabai -m rule --add app="^Firefox$" space=browse
yabai -m rule --add app="^Firefox Developer Edition$" space=browse
yabai -m rule --add app="^Safari$" space=browse
yabai -m rule --add app="^Chromium$" space=browse
yabai -m rule --add app="^Google Chrome$" space=browse

# dev
yabai -m rule --add app="^Alacritty$" space=dev
yabai -m rule --add app="^Visual Studio Code$" space=dev

# chat
yabai -m rule --add app="^Discord$" space=chat
yabai -m rule --add app="^Telegram$" space=chat
yabai -m rule --add app="^Slack$" space=chat
yabai -m rule --add app="^Microsoft Outlook$" space=chat
yabai -m rule --add app="^WhatsApp$" space=chat

echo "yabai configuration loaded.."
