import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.95
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
