import = ["~/.config/alacritty/everforest-dark.toml"]

[font]
size = 16.0

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 1
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
