
[font]
size = 16.0

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 1
blur = true
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[general]
import = ["~/.config/alacritty/everblush.toml"]

[env]
TERM = "xterm-256color"
